import { Platform, PlatformIOSStatic } from "react-native";
import colors from "./colors";

const cssConstants = {
    DEFAULT_ANIMATION_DURATION: 300,

    TAB_BAR_GAP: 10,

    //heights
    INPUT_HEIGHT: 40,
    HEADER_HEIGHT: 40,
    TOOLBAR_HEIGHT: 60,

    // icon size
    SIZE: 30,

    //radius
    BASE_BORDER_RADIUS: 6,
    EXTRA_BASE_BORDER_RADIUS: 10,
    INPUT_BORDER_RADIUS: 4,

    // Fonts
    BASE_FONT_SIZE: 14,
    SMALL_FONT_SIZE: 12,
    LARGE_FONT_SIZE: 20,
    MEDIUM_FONT_SIZE: 16,
    EXTRA_LARGE_FONT_SIZE: 28,
    HEADER_FONT_SIZE: 18,
    INPUT_FONT_SIZE: 16,
    ICON_SIZE: 20,
    LARGE_ICON_SIZE: 32,
    EXTRA_SMALL_FONT_SIZE: 10,

    ICON_SIZE_LARGE: 40,
    // margin
    DEFAULT_MARGIN: 10,
    XXX_SMALL_MARGIN: 2,
    XX_SMALL_MARGIN: 4,
    X_SMALL_MARGIN: 8,
    SMALL_MARGIN: 12,
    MEDIUM_MARGIN: 16,
    LARGE_MARGIN: 20,
    X_LARGE_MARGIN: 24,
    XX_LARGE_MARGIN: 32,

    //padding
    DEFAULT_PADDING: 10,
    XXX_SMALL_PADDING: 2,
    XX_SMALL_PADDING: 4,
    X_SMALL_PADDING: 8,
    SMALL_PADDING: 12,
    MEDIUM_PADDING: 16,
    LARGE_PADDING: 20,
    X_LARGE_PADDING: 24,
    XX_LARGE_PADDING: 32,


    //Shadow
    SHADOW_COLOR: colors.BLACK,
    SHADOW_OPACITY: 0.2,

    // Colors
    WHITE_COLOR: colors.WHITE,
    TRANSPARENT_COLOR: colors.TRANSPARENT,
    PRIMARY_COLOR: colors.PRIMARY.PRIMARY_500,
    LIGHT_PRIMARY_COLOR: colors.PRIMARY.PRIMARY_100,
    DARK_PRIMARY_COLOR: colors.PRIMARY.PRIMARY_900,
    SECONDARY_COLOR: colors.SECONDARY.SECONDARY_500,
    BACKGROUND_COLOR: colors.WHITE,
    DISABLE_COLOR: colors.NEUTRAL.NEUTRAL_40,
    // INFO_BACKGROUND: colors.BLUE.MAYA_BLUE,
    BORDER_COLOR: '#D7DCE3',//colors.SECONDARY.SECONDARY_50,
    LIGHT_BORDER_COLOR: colors.NEUTRAL.NEUTRAL_30,
    WARNING_BACKGROUND: colors.DANGER.DANGER_300,
    TEXT_COLOR: colors.NEUTRAL.NEUTRAL_600,
    LIGHT_TEXT_COLOR: colors.NEUTRAL.NEUTRAL_200,
    DANGER_TEXT_COLOR: colors.DANGER.DANGER_500,
    PLACEHOLDER_TEXT_COLOR: colors.NEUTRAL.NEUTRAL_100,
    OVERLAY_BACKGROUND_COLOR: colors.BLACK + 'BB', //'#000000' + 'BB'
    INPUT_BACKGROUND_COLOR: colors.WHITE,

    isIpad: (Platform.OS == 'ios' && (Platform as PlatformIOSStatic).isPad),

    PICKER_CIRCLE_HEIGHT: 15,
    PICKER_CIRCLE_WIDTH: 15,
    PICKER_BORDER_RADIUS: 10
};

export default cssConstants;
