import colors from "./rn-colors";

const rnConstants = {
    //heights
    SMALL_INPUT_HEIGHT: 28,
    INPUT_HEIGHT: 40,
    LARGE_INPUT_HEIGHT: 44,
    HEADER_HEIGHT: 40,

    //radius
    BASE_BORDER_RADIUS: 6,
    INPUT_BORDER_RADIUS: 4,
    CHIP_RADIUS: 8,

    // Fonts
    BASE_FONT_SIZE: 14,
    SMALL_FONT_SIZE: 12,
    LARGE_FONT_SIZE: 20,
    MEDIUM_FONT_SIZE: 16,
    INPUT_FONT_SIZE: 16,
    EXTRA_SMALL_FONT_SIZE: 10,

    //Icon
    ICON_SIZE: 20,

    // margin
    DEFAULT_MARGIN: 10,

    //padding
    DEFAULT_PADDING: 10,
    XXX_SMALL_PADDING: 2,
    XX_SMALL_PADDING: 4,

    // Picker
    PICKER_CIRCLE_HEIGHT: 15,
    PICKER_CIRCLE_WIDTH: 15,
    PICKER_BORDER_RADIUS: 10,

    // Colors
    BODY: colors.BODY,
    BLACK_COLOR: colors.BLACK,
    WHITE_COLOR: colors.WHITE,
    TRANSPARENT_COLOR: colors.TRANSPARENT,

    LIGHT_PRIMARY_COLOR: colors.PRIMARY.PRIMARY_50,
    PRIMARY_COLOR: colors.PRIMARY.PRIMARY_500,
    DARK_PRIMARY_COLOR: colors.PRIMARY.PRIMARY_900,

    SECONDARY_COLOR: colors.SECONDARY.SECONDARY_500,
    DARK_SECONDARY_COLOR: colors.SECONDARY.SECONDARY_900,

    DANGER_COLOR: colors.DANGER.DANGER_500,
    DARK_DANGER_COLOR: colors.DANGER.DANGER_900,

    LIGHT_NEUTRAL_COLOR: colors.NEUTRAL.NEUTRAL_20,
    NEUTRAL_COLOR: colors.NEUTRAL.NEUTRAL_50,
    MEDIUM_NEUTRAL_COLOR: colors.NEUTRAL.NEUTRAL_80,
    DARK_NEUTRAL_COLOR: colors.NEUTRAL.NEUTRAL_900,

    SUCCESS_COLOR: colors.SUCCESS.SUCCESS_500,
    DARK_SUCCESS_COLOR: colors.SUCCESS.SUCCESS_900,

    WARNING_COLOR: colors.DANGER.DANGER_50,
    DARK_WARNING_COLOR: colors.DANGER.DANGER_400,

    BACKGROUND_COLOR: colors.WHITE,
    WARNING_BACKGROUND: colors.DANGER.DANGER_300,

    // Text Colors
    TEXT_COLOR: colors.NEUTRAL.NEUTRAL_600,
    LIGHT_TEXT_COLOR: colors.NEUTRAL.NEUTRAL_200,
    DANGER_TEXT_COLOR: colors.DANGER.DANGER_500,

    BORDER_COLOR: colors.SECONDARY.SECONDARY_50,
    DISABLE_COLOR: colors.NEUTRAL.NEUTRAL_40,
};

export default rnConstants;
